knp_ipsum_doctrine_odm:
    path: /doctrine-odm
    defaults: { _controller: KnpIpsumBundle:DoctrineOdm:index }

knp_ipsum_doctrine_odm_create:
    path: /doctrine-odm/create
    defaults: { _controller: KnpIpsumBundle:DoctrineOdm:create }

knp_ipsum_doctrine_odm_delete:
    path: /doctrine-odm/delete/{id}
    defaults: { _controller: KnpIpsumBundle:DoctrineOdm:delete }
    requirements:
        id: ^[0-9a-z]*$
