knp_ipsum_doctrine_orm:
    path:  /doctrine-orm
    defaults: { _controller: KnpIpsumBundle:DoctrineOrm:index }

knp_ipsum_doctrine_orm_create:
    path:  /doctrine-orm/create
    defaults: { _controller: KnpIpsumBundle:DoctrineOrm:create }

knp_ipsum_doctrine_orm_customrepository:
    path:  /doctrine-orm/custom-repository
    defaults: { _controller: KnpIpsumBundle:DoctrineOrm:customRepository }

knp_ipsum_doctrine_orm_delete:
    path:  /doctrine-orm/delete/{id}
    defaults: { _controller: KnpIpsumBundle:DoctrineOrm:delete }
    requirements:
        id: ^\d+$
