knp_ipsum_jms_securityextra:
    path:  /secured/jms-securityextra
    defaults: { _controller: KnpIpsumBundle:JMSSecurityExtra:index }

knp_ipsum_jms_securityextra_admin:
    path:  /secured/jms-securityextra/admin
    defaults: { _controller: KnpIpsumBundle:JMSSecurityExtra:admin }
