knp_ipsum_login:
    path:  /secured/login
    defaults: { _controller: KnpIpsumBundle:Secured:login }
    
_security_check:
    path:  /secured/login_check
    defaults: { _controller: KnpIpsumBundle:Secured:securityCheck }
    
knp_ipsum_logout:
    path:  /secured/logout
    defaults: { _controller: KnpIpsumBundle:Secured:logout }
    
knp_ipsum_secured:
    path:  /secured
    defaults: { _controller: KnpIpsumBundle:Secured:index }

knp_ipsum_secured_admin:
    path:  /secured/admin
    defaults: { _controller: KnpIpsumBundle:Secured:admin }
