knp_ipsum_swiftmailer:
    path:  /swiftmailer
    defaults: { _controller: KnpIpsumBundle:Swiftmailer:index }

knp_ipsum_swiftmailer_send:
    path:  /swiftmailer/send
    defaults: { _controller: KnpIpsumBundle:Swiftmailer:send }
